# Generated by Django 4.1.7 on 2023-03-12 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='flight_details_Model',
            new_name='FlightDetailsModel',
        ),
    ]
